spring.application.name=EarthHub

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/earthhub_db
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (Useful for Phase 1 debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
